apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubevalidator
  namespace: kubevalidator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubevalidator
  template:
    metadata:
      labels:
        app: kubevalidator
    spec:
      containers:
        - name: kubevalidator
          image: gcr.io/rancho-de-newland/kubevalidator
          envFrom:
          - configMapRef:
              name: kubevalidator
          - secretRef:
              name: kubevalidator
