apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/enable-cors: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  name: kubevalidator
  namespace: kubevalidator
spec:
  rules:
  - host: kubevalidator.k.jnewland.com
    http:
      paths:
      - backend:
          serviceName: kubevalidator
          servicePort: 8080
        path: /
  tls:
  - hosts:
    - kubevalidator.k.jnewland.com
    secretName: kubevalidator-tls
