apiversion: v1alpha
kind: KubeValidatorConfig
spec:
  manifests:
  - glob: config/kubernetes/default/*/*.yaml
    schemas:
    - version: 1.10.0
      strict: true
  # Test yoself
  - glob: fixtures/line-numbers/*.yaml
    schemas:
    - version: 1.10.0
      strict: true
