repository:
  description: A GitHub App that uses kubeval to validate all of that Kubernetes YAML in your repo
  topics: github, github-app, kubernetes, yaml, ci
  private: true
  has_projects: false
  has_wiki: false
  default_branch: master

branches:
  - name: master
    protection:
      required_pull_request_reviews: null
      required_status_checks:
        strict: true
        contexts:
        - kubevalidator
        - YAMBURGER
        - Build
        - WIP
      enforce_admins: true
      restrictions: null
