repository:
  description: A GitHub App that uses kubeval to validate all of that Kubernetes YAML in your repo
  homepage: https://github.com/apps/kubevalidator
  topics: github, github-app, kubernetes, yaml, yml, ci, kubectl, lint, linter
  private: false
  has_projects: false
  has_wiki: false
  default_branch: master

branches:
  - name: master
    protection:
      required_pull_request_reviews:
        require_code_owner_reviews: true
        dismiss_stale_reviews: true
      required_status_checks:
        strict: true
        contexts:
        - kubevalidator
        - YAMBURGER
        - Build
      restrictions: null
