repository:
  description: A GitHub App that uses kubeval to validate all of that Kubernetes YAML in your repo
  homepage: https://github.com/apps/kubevalidator
  topics: github, github-app, kubernetes, yaml, yml, ci, kubectl, lint, linter
  private: false
  has_projects: false
  has_wiki: false
  default_branch: master

branches:
  - name: master
    protection:
      required_pull_request_reviews: null
      required_status_checks:
        strict: true
        contexts:
        - YAMBURGER
        - kubevalidator
        - Build (677203284384)
      enforce_admins: false
      restrictions: null
