# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[constraint]]
  name = "github.com/google/go-github"
  source = "github.com/urcomputeringpal/go-github"
  revision = "f67f03765936eb4a6b08a37ea7565f54e795ea23"

[[constraint]]
  name = "github.com/garethr/kubeval"
  version = "0.7.1"

[[constraint]]
  name = "github.com/bradleyfalzon/ghinstallation"
  version = "0.1.2"

[[constraint]]
  name = "github.com/go-test/deep"
  branch = "master"

[[constraint]]
  name = "github.com/krishicks/yaml-patch"
  branch = "master"

[[constraint]]
  name = "github.com/pmezard/go-difflib"
  branch = "master"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"
  source = "github.com/go-yaml/yaml"
